### ISSUE TITLE
The find function issue

### ISSUE THREAD

**Issue by srambhatla** [scottsievert/swix#13]
the ```find``` function pretty much returns the original matrix. Modify it to take a logical statement like ```find (X > 0)``` and return 
1. ```argwhere (X  > 0 )```
2.  ```X [ argwhere( X  > 0 ) ]```
this will also make it more ```MATLAB``` like.

**Comment by scottsievert** [comment]
This was very recently addressed by 0fa894959406fd706f94372e6ee7da72275b878b! This commit removed `find` as I find `argwhere` more clear about what it does than `find`.
