### ISSUE TITLE
Seeding random variables 

### ISSUE THREAD

**Issue by srambhatla** [scottsievert/swix#14]
Random numbers currently have a fixed seed. Would be nice to have a command to control it. For e.g. ```MATLAB``` has ```rng``` for this.

**Comment by scottsievert** [comment]
Closed.

A new global variable was defined in `numbers.swift` called `SWIX_SEED`. The call to LAPACK's [`dlarv`][1] updates the seed each time (the reason this fix wasn't as simple as I thought).

[1]:http://netlib.org/lapack/lapack-3.1.1/html/dlarnv.f.html
