### ISSUE TITLE
Could you update this library for the latest version of Swift (~2.1)?

### ISSUE THREAD

**Issue by shyamalschandra** [scottsievert/swix#15]
Could you update the code for this library for the latest version of Swift?

Thanks!

**Comment by scottsievert** [comment]
When I run swix under Xcode 7.1 beta 7B75 (the latest release; just downloaded it) I successfully compile and all the tests pass in `swixTests`. Are you sure you're running the most recent version? I know I update for Xcode 7 beta 6 in d402765d04432ed39894381d71c096e2ed3a8d5a on August 31st.
